engines:
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript

ratings:
   paths:
   - "**.rb"
   - "**.scss"
