engines:
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
    exclude_paths:
    - "spec/"
    - "db/"
    - "e2e-tests/"
    - "**.spec.js"
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true

ratings:
   paths:
   - "**.rb"
   - "**.scss"
   - Gemfile.lock
