AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
Style/Documentation:
  Exclude:
    - 'db/migrate/*'
