AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'spec/**/*'
    - 'app/controllers/application_controller.rb'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'god.rb'
Rails:
  Enabled: true
Rails/TimeZone:
  Exclude:
    - 'app/jobs/schedule.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/services/backend_service.rb'
Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/services/backend_service.rb'
Metrics/AbcSize:
  Max: 20
  Exclude: 
    - 'app/services/backend_service.rb'
Metrics/CyclomaticComplexity:
  Max: 7
Style/FrozenStringLiteralComment:
  Enabled: False
Style/Documentation:
  Exclude:
    - 'app/models/*'
    - 'app/helpers/*'
Style/AccessorMethodName:
  Exclude: 
    - 'app/services/backend_service.rb'