language: ruby
rvm:
  - 2.3.0

before_install:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle exec rails server -p 3000 &
  - sleep 5

script:
  - bundle exec rake
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox

notifications:
  email: false
