language: ruby
rvm:
  - 2.3.0

before_install:
  - npm install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake
  - npm test

notifications:
  email: false
